### PR TITLE
Edited social media links, contents and looks

### PR DESCRIPTION
**Pull request by nardos-negussie**

### CODE REVIEW

**Comment by smigad** [comment]
you're a little behind. you should pull new changes before a pullrequest

**Comment by nardos-negussie** [comment]
I've pulled, updated my repo, and pushed back.

**Comment by nardos-negussie** [comment]
Dear Mr. Dagim

I'm sorry i couldn't make it today. But, in the attached files you'll find
the assignment(s).
The zip file is the first assignment(task 2), please find and read the
readme file in it, it explains how i've done it and hope to hear your
feedback on it.

And for the last week's assignment, i prepared a demo of the commands, and
the demo for each command.

**Comment by nardos-negussie** [comment]
I think it's better if i send you the commands to see'em better. I attached
it(commands.png).

with regards.

**Pull request merged**
